/**
 * Tailwind Static Build Configuration
 * 扫描全部 HTML 文件提取已用 class，生成最小化 CSS（替代 CDN 运行时编译）
 */
module.exports = {
    plugins: [
        require('@tailwindcss/forms'),
    ],
    content: [
        './**/*.html',
        '!./node_modules/**',
        '!./.git/**',
        '!./TEXT/**',
        '!./.bak/**',
    ],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                'primary': '#a33e00',
                'surface-dim': '#dadada',
                'on-tertiary-fixed-variant': '#00497b',
                'surface-container-low': '#f3f3f3',
                'surface-container-highest': '#e2e2e2',
                'surface-container-high': '#e8e8e8',
                'on-primary': '#ffffff',
                'on-primary-container': '#561d00',
                'on-error': '#ffffff',
                'primary-container': '#ff6600',
                'on-secondary-fixed': '#1b1c1c',
                'secondary': '#5f5e5e',
                'on-surface': '#1a1c1c',
                'on-secondary-container': '#656464',
                'surface-tint': '#a33e00',
                'surface': '#f9f9f9',
                'surface-variant': '#e2e2e2',
                'secondary-fixed': '#e4e2e1',
                'error-container': '#ffdad6',
                'surface-container-lowest': '#ffffff',
                'on-secondary-fixed-variant': '#474747',
                'inverse-on-surface': '#f1f1f1',
                'tertiary-container': '#009cfc',
                'surface-container': '#eeeeee',
                'on-tertiary-container': '#003155',
                'on-tertiary': '#ffffff',
                'on-error-container': '#93000a',
                'on-primary-fixed-variant': '#7c2e00',
                'error': '#ba1a1a',
                'inverse-surface': '#2f3131',
                'on-primary-fixed': '#360f00',
                'secondary-container': '#e4e2e1',
                'on-background': '#1a1c1c',
                'tertiary': '#0062a1',
                'surface-bright': '#f9f9f9',
                'on-secondary': '#ffffff',
                'secondary-fixed-dim': '#c8c6c6',
                'primary-fixed-dim': '#ffb596',
                'tertiary-fixed-dim': '#9ccaff',
                'outline': '#8e7164',
                'inverse-primary': '#ffb596',
                'primary-fixed': '#ffdbcd',
                'on-surface-variant': '#5a4136',
                'outline-variant': '#e3bfb1',
                'background': '#f9f9f9',
                'tertiary-fixed': '#d0e4ff',
                'on-tertiary-fixed': '#001d35',
            },
            borderRadius: {
                'DEFAULT': '0.125rem',
                'lg': '0.25rem',
                'xl': '0.5rem',
                'full': '0.75rem',
            },
            spacing: {
                'gutter': '24px',
                'container-max': '1280px',
                'base': '8px',
                'section-gap': '120px',
                'margin-desktop': '64px',
                'margin-mobile': '20px',
            },
            fontFamily: {
                'headline-md': ['Inter'],
                'display-lg-mobile': ['Inter'],
                'headline-lg': ['Inter'],
                'display-lg': ['Inter'],
                'body-md': ['Inter'],
                'label-md': ['Inter'],
                'body-lg': ['Inter'],
            },
            fontSize: {
                'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
                'display-lg-mobile': ['40px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
                'headline-lg': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
                'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
                'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
                'label-md': ['14px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
                'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
            },
        },
    },
};
